server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false
  # Flyway 데이터베이스 마이그레이션 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s
      password: pinup2025@
  # 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1시간
      cache-null-values: false
# JWT 설정
jwt:
  secret: ${JWT_SECRET:pVQgJfFKqOz1lfzVOjiTNrGsL3bo8bvbYB51YJFQ56sY0iWYs2LaV65BeBDaed3a}
  expiration: 86400000 # 24시간(ms)
  refresh-expiration: 604800000 # 7일(ms)

# 로깅 설정
logging:
  level:
    root: INFO
    com.beboard: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE