server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: prod
    include: secret
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false
  # Flyway 데이터베이스 마이그레이션 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1시간
      cache-null-values: false

# 로깅 설정
logging:
  level:
    root: INFO
    com.beboard: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES # 사용되는 알고리즘
    pool-size: 2 # 암호화 요청을 담고 있는 pool의 크기
    string-output-type: base64 # 암호화 이후에 어떤 형태로 값을 받을지 설정
    key-obtention-iterations: 1000 # 암호화 키를 얻기 위해 반복해야 하는 해시 횟수
    password: ${JASYPT_KEY} # 환경변수 설정