# JWT 설정
jwt:
  secret: ENC(WrRgBS6Yfe53ai58sv+2XsgMHz7dchfb5rWadtTvvOfBsrXa77GJDOHItyOkNb2/zAbMuZoWXqsE+9dFt//kiUxzayPh+eTXbB8Ha0rUZqw=)
  access-token-expiration: 86400000 # 24시간(ms)
  refresh-token-expiration: 604800000 # 7일(ms)

