spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(o61AvS9Hzcfv7l3xJxUGuTmzz9e5ARE/JjmdQom3M5+jx/jcwGrMq9/tav2aCJ8Af0AnCJsIqTP36TPayOpvFppn+Of6asnUWTpQv4yr2HbMviBM807iqP6UhB7S1h3lmnAWGi9iTsFUAzgP2epG5dTVZCwNoKkpOdOwt7IeocK8Oh/ItRYxSo2BVLCr8UzemcNozbD/IYOu/MNuZPqhpw==)
    username: ENC(KECJYP3aLTAaS/1ffwfn2Q==)
    password: ENC(dH70a8PAfeYkwJ/fS9oTCyQ7nIM9QfYhlVqbVF+T/0A=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true # 콘솔창에 출력되는 SQL문을 사람이 보기 편한 형태로 출력
        default_batch_fetch_size: 500 # 1:N 컬렉션 조회 시 성능 최적화
        highlight_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ENC(+mNfUF8iXbnTe2oQ58Z2WA==)
      port: 6379
      timeout: 10s
      password: ENC(KnkqTTSRRexaS5ibCJb8ecv8MC/mQF9a)