spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/board?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true # 콘솔창에 출력되는 SQL문을 사람이 보기 편한 형태로 출력
        default_batch_fetch_size: 500 # 1:N 컬렉션 조회 시 성능 최적화
        highlight_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true