name: CI/CD
on:
  push:
    branches:
      - main

env:
  DOCKER_COMPOSE_PATH: "/home/ubuntu/docker-compose.yml"
  JASYPT_KEY: ${{ secrets.JASYPT_KEY }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Seoul'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Execute Permission For Gradlew
        run: chmod +x ./gradlew

      - name: Clean And Test With Gradle
        run: ./gradlew clean -x test --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image Build And Push
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}-board:${{ github.sha }} . --push

      - name: Deploy to dev EC2
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DOCKER_COMPOSE_PATH, JASYPT_KEY
          script: |
            sudo docker compose down || true
            sudo docker rmi $(docker images -q) -f || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}-board
            export JASYPT_KEY=$JASYPT_KEY
            sudo docker compose up -f $DOCKER_COMPOSE_PATH up -d